### ISSUE TITLE
Workspace with mysql fails to start because of outdated helm chart

### ISSUE THREAD

**Issue by sleshchenko** [che-incubator/chectl#106]
mysql container requires to be run with non-root user.
![Screenshot from 2019-05-24 10-32-33](https://user-images.githubusercontent.com/5887312/58314137-8c9da500-7e17-11e9-85ac-2c05ae160f9b.png)
The following Devfile may be used to reproduce an issue https://gist.githubusercontent.com/sleshchenko/86aa2e010375bc2a472aa3fa6adaaf18/raw/92cb073a2f4124d7445c454e9207a5abc2512f25/petclinic.k8s.devfile.yaml

Helm chart in upstream Che is updated and non-root user is used by default.
Workspace with mysql fails to start because of an outdated helm chart state.

It's pretty easy to copy/paste helm chart from Che Repo but I decided to create this issue to raise a topic of copying/pasting helm chart, only a few people are aware of existence of copy for Che Helm chart in chectl repo and nobody does the same changes which are done for upstream Che.

This issue is about investigation whether it is possible to avoid having a duplicate of Che Helm Chart for Chectl.

**Comment by benoitf** [comment]
what are the options there ?

git submodules ?
cloning che helm folder as part of pre-hooks scripts ?
