### ISSUE TITLE
Workspace created from devfile can't be opened

### ISSUE THREAD

**Issue by Ohrimenko1988** [che-incubator/chectl#123]
### Reproduction steps:
 - Deploy che to minikube by the latest chectl
 - Create workspace from devfile https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/c8dfc7a3c3292bb822445f0c9b68af9bf93a68a0/devfile.yaml
 - Open workspace and wait until it running

**Expected result:**
Workspace is successfully started

**Observed result:**
Workspace output shows that all plugins successfully processed and started, but workspace is stuck on the loading page.
If navigate to the dashboard and try to reopen workspace we receive next result:
![Screenshot from 2019-06-01 11-32-15](https://user-images.githubusercontent.com/22724619/58746740-77092a80-846a-11e9-9de4-dce4aba1fb3b.png)

**Comment by Ohrimenko1988** [comment]
It looks like the problem related to plugin:
```
- type: chePlugin
  id: ms-kubernetes-tools/vscode-kubernetes-tools/latest
```
If remove this plugin and instead add 
```
- type: cheEditor
    id: eclipse/che-theia/next
```
all work properly

**Comment by l0rd** [comment]
Closing this issue since it's related to kubernetes tooling
