### ISSUE TITLE
Starting server fails on mac os x when starting pods

### ISSUE THREAD

**Issue by titusn** [che-incubator/chectl#124]
I tried using `chectl` to start a stand-alone che server. I previously managed to get it running just using the old-fashioned `docker run` command. That worked, but I ran into trouble creating projects (see https://stackoverflow.com/questions/56415583/eclipse-che-7-node-js-error-this-workspace-is-using-old-definition-format-which), which seemed fair, as I was following a method meant for che 6.

During start up I consistently got the error `ERR_TIMEOUT: Timeout set to pod ready timeout 130000` when chectl tried to start the pods. I tried:
- deleting all docker containers, cache, volumes and images
- reinstalling minikube
- running minikube by hand (see error log below)
- deleting the chectl server
- raising memory of minikube to 4096 MB
- raising the pod timeout
- using a different kubernetes cluster (unfortunately docker4mac was not supported, even though the quick-start guide suggests it should be possible)

### Expected behaviour

`chectl` is able to start the pods after downloading the images

### Observed behaviour

chectl errors out:

`chectl server:start --k8spodreadytimeout=500000`

    ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.100.nip.io.
    ✔ 🏃‍  Running Helm to install Che
      ✔ Verify if helm is installed
      ✔ Create Tiller Role Binding...it already exist.
      ✔ Create Tiller Service Account...it already exist.
      ✔ Create Tiller RBAC
      ✔ Create Tiller Service...it already exist.
      ✔ Preparing Che Helm Chart...done.
      ✔ Updating Helm Chart dependencies...done.
      ✔ Deploying Che Helm Chart...done.
    ❯ ✅  Post installation checklist
      ❯ Che pod bootstrap
        ✔ scheduling...done.
        ✔ downloading images...done.
        ✖ starting
          → ERR_TIMEOUT: Timeout set to pod ready timeout 500000
        Retrieving Che Server URL
        Che status check
    Error: ERR_TIMEOUT: Timeout set to pod ready timeout 500000
        at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
        at Generator.next (<anonymous>)
        at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)

### Steps to reproduce

1. Under Mac OS High Sierra use homebrew to install minikube, helm and chectl.
2. Run `chectl server:start`

**Comment by ye1984** [comment]
Same issue.... and same config as you

**Comment by azatsarynnyy** [comment]
There's Che Server [issue](https://github.com/eclipse/che/issues/13463) which is already [fixed](https://github.com/eclipse/che/pull/13466) but a docker image hasn't been updated yet.
So if you don't require to get the latest changes I can suggest you start Che with `7.0.0-beta-5.0` version for example.
`chectl server:start --cheimage=eclipse/che-server:7.0.0-beta-5.0`

**Comment by titusn** [comment]
Thank you for the answer. I can confirm that starting that version works. The first time I tried I did get the following error:

`  ❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✖ starting
        → Get pods by selector "app=che" returned a pod with an invalid status.conditions
      Retrieving Che Server URL
      Che status check
Error: Get pods by selector "app=che" returned a pod with an invalid status.conditions
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)`

On a retry it just worked. The first time it seemed like downloading the image took almost no time, so probably it didn't download the other image immediately.

**Comment by azatsarynnyy** [comment]
FYI: `nightly` image has been already updated, so `chectl server:start` w/o params successfully starts Che Server

**Comment by ye1984** [comment]
@titusn same as you :) it works with the image given by @azatsarynnyy
