### ISSUE TITLE
chectl workspace:start --devfile=devfile.yaml not working

### ISSUE THREAD

**Issue by ye1984** [che-incubator/chectl#126]
Hello,

An error is occured when I run this command  `chectl workspace:start --devfile=devfile.yaml`

> Error: workspace:start command is expecting a devfile or workspace configuration 
 ›   parameter.

And the source (start.ts):
`if (!flags.devfile && !flags.workspaceconfig) {
      this.error('workspace:start command is expecting a devfile or workspace configuration parameter.')
    }`

I don't understand why the workspace config is necessary ?

Stack: `chectl/0.0.2-254bc44 darwin-x64 node-v10.15.3`

**Comment by benoitf** [comment]
Hello,
it's either the devfile or the workspace config that is mandatory, not the both


```
./bin/run workspace:start --devfile=/tmp/foo
  ✔ Retrieving Che Server URL...http://che-che.192.168.99.125.nip.io
  ✔ Verify if Che server is running
  ✔ Create workspace from Devfile /tmp/foo
```

**Comment by benoitf** [comment]
Kamino closed and cloned this issue to [eclipse/che](https://github.com/eclipse/che/issues/14457)
