### ISSUE TITLE
keycloak: pods not scheduling as persistent volumes created in different (aws) availability zones

### ISSUE THREAD

**Issue by szab100** [che-incubator/chectl#1265]
## Where to report issues?

This is about 'chectl' / helm charts.

We are unable to install on AWS EKS K8S clusters, as the keycloak-log and keycloak-data PVs are getting created on different availability zones and the Deployment's pods are stuck at Pending. I don't see where / how the keycloak's PVCs / PVs are getting created. There is nothing related in its templates/ folders, I guess it is somehow dynamically created by 'chectl', but since they don't have failure-domain.beta.kubernetes.io/zone labels set, the PVs are getting created in different zones and the Deployment's pods are stuck in Pending status as EKS does not allow pods mounting volumes from different zones.

Can you please help us resolve this? Thanks!

**Comment by szab100** [comment]
oops, It seems I was completely blind today.. just found the keycloak-*-claim.yaml files where I added these to their spec:
  {{- if .Values.global.cheKeycloakLogPVCStorageClassName }}
  storageClassName: {{ .Values.global.cheKeycloakLogPVCStorageClassName }}
  {{- end }}

and 

  {{- if .Values.global.cheKeycloakDataPVCStorageClassName }}
  storageClassName: {{ .Values.global.cheKeycloakDataPVCStorageClassName }}
  {{- end }}

I can create a PR once we are all done.. let me leave the issue open till then

**Comment by nickboldt** [comment]
This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at https://github.com/eclipse/che/issues.

If you plan to submit a PR, please open an issue at the above link, so it can be referenced in your PR's commit message and details.
