### ISSUE TITLE
Support Kubernetes embedded in Docker for mac

### ISSUE THREAD

**Issue by skabashnyuk** [che-incubator/chectl#14]
Minikube running on Virtualbox is quite a heavy. It would be nice to allow using built-in Kubernetes in Docker for Mac.

**Comment by l0rd** [comment]
You can/should use the [hyperkit driver](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver) if you are on macOS

**Comment by l0rd** [comment]
Anyway yes I have asked @benoitf if he could work on that
