### ISSUE TITLE
--cheimage parameter has no effect during deploying Multiuser Che on minikube

### ISSUE THREAD

**Issue by sleshchenko** [che-incubator/chectl#161]
### Description
--cheimage parameter has no effect during deploying Multiuser Che on minikube

### Reproducing
1. Deploy Multiuser Che on minikube with chectl
```
chectl server:start --platform=minikube --cheimage=sleshchenko/che-server:demo -m
```
2. Check Che Server image that is used.
Expected: `sleshchenko/che-server:demo` is used as image for Che Server
Actual: `eclipse/che-server:latest` is used as image for Che Server.

--cheimage works fine for single-user Che installation ( if -m arg is missing)

**Comment by benoitf** [comment]
I've proposed a PR
