### ISSUE TITLE
chectl with custom che assembly

### ISSUE THREAD

**Issue by 781227k** [che-incubator/chectl#165]
Hi chectl team,

I have developed ws-agent extensions based on che-6 and build a custom che assembly with custom docker cli accordingly to che-6 documentation. How can I extend chectl so that it uses my che assembly and my plugins will still be available for GWT-IDE with new kubernetes structure.

Thanks in advance.

**Comment by benoitf** [comment]
There is a parameter/config to override the default che-server image when using `server:start`, so if you've deployed your new-all-in-one assembly in a che-server image then it will used that image instead of default che-server docker image.

**Comment by fErten** [comment]
@benoitf thanks for the answer, I see that now it is in [src/commands/server/start.ts](https://github.com/che-incubator/chectl/blob/1de1bd9fa7c29b061a7c9d98c3fca46c20dd558e/src/commands/server/start.ts) , is it also configurable to pull the che-server image from a private docker registry?

**Comment by benoitf** [comment]
@fErten I would say that if you specify the full pattern to the docker image (including registry) and that the host is configured to access this private registry it should work as well
