### ISSUE TITLE
chectl not working on Windows

### ISSUE THREAD

**Issue by danidoedel** [che-incubator/chectl#167]
Chectl doesn't seem to do anything as nothing happens typing it into cmd or powershell.
I would highly appreciate if some has an idea what could be wrong.
kubectl, minikube, helm are installed. Using Windows 10 version 1809.
If you need additional information, just let me know.

![image](https://user-images.githubusercontent.com/10995998/59464088-d4688880-8e27-11e9-97ed-1837ef29885f.png)

**Comment by benoitf** [comment]
thanks for the report @danidoedel 
I will check
