### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [che-incubator/chectl#177]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/che-incubator/chectl/blob/master/package.json#L32

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by benoitf** [comment]
yes, correct somehow it's not used (also we're relying on fs-extra)

**Comment by benoitf** [comment]
once reviewed, will be closed by https://github.com/che-incubator/chectl/pull/178
