### ISSUE TITLE
Exit with error if minikube is not running

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#20]
We currently try to start `minikube` when it's stopped. The problem with that approach is that `minikube` bootstrap may fail for different reasons we cannot control and the user won't be able to understand if the error comes from `minikube` or from `chectl`.

We should instead display an error message if minikube is not started. The message should contain instructions to start minikube correctly.

**Comment by qurben** [comment]
Reasons why minikube cannot be started on Windows (non-exhaustive list):

 - Command prompt is not an Administrator prompt and the kubernetes environment in not created
 - User wants to use Hyper-V with minikube where it defaults to VirtualBox
