### ISSUE TITLE
MicroK8S OIDC

### ISSUE THREAD

**Issue by elielam** [che-incubator/chectl#2096]
Hello,

I am currently having a problem installing eclipse che via chectl on microk8s.

The problem in question lies in the identification of the OIDC parameters of kubernetes.

I obviously (not without difficulty) took care to activate OIDC via keycloak by adding in `/var/snap/microk8s/current/args/kube-apiserver` the right arguments on my node and it works very well via kubectl.

![image](https://user-images.githubusercontent.com/34446626/166156156-56e100ab-d3fc-4586-95ab-22ed2b6f8315.png)

However chectl fails to pass the verification step of my OIDC configuration.

I initially disabled the check via the `--skip-oidc-provider-check` argument but that only delayed the problem, the process finished on a timeout because the `oauth-proxy` container of the `che-gateway` pod crashed with the following message: "... oidc-issuer-url is required".

Looking closer in the code it appears that in the [file](https://github.com/che-incubator/chectl/blob/main/src/commands/server/deploy.ts)  we are looking in the `kube-system` namespace for a pod with the label `component=kube-apiserver`.

Here :

    function ensureOIDCProviderInstalled(flags: any): Listr.ListrTask {
        ...
        const apiServerPods = await kube.getPodListByLabel('kube-system', 'component=kube-apiserver')

When I check in this namespace this is what I found : 

![image](https://user-images.githubusercontent.com/34446626/166156112-6776f9d2-ac3b-49ad-a44c-0be234676a25.png)

The closest reference I find to what we are looking for is in the `default` namespace on the `kubernetes ` service but i can't find to wich pod is it related.

![image](https://user-images.githubusercontent.com/34446626/166156270-5e11b037-f626-43c6-a61b-dee2655474b7.png)

Search pods with corresponding label : 

![image](https://user-images.githubusercontent.com/34446626/166156287-8820c9fa-3b73-4b27-adda-fbc982c7d834.png)

Is my microk8s installation having a problem or am I missing something on the OIDC or chectl ?

Plateform : `Linux servername 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`
Microk8s : `Microk8s v1.21.11`
Kubectl : `v1.22.4`
Kubernetes : `v1.21.11-3+2bdf0a81ac1652`

Thank you in advance (sorry for my bad english) !

**Comment by migueldacostarego** [comment]
+1
