### ISSUE TITLE
More specific error prompts

### ISSUE THREAD

**Issue by mosn** [che-incubator/chectl#238]
Posting here since I am not sure if this needs even time at this satge. 

Prompts that shown for input error are generalized and not very specific. While errors are being handled, this is  more about the message that is shown. i.e

some older version : `--platform=k8s`
error: ¯\_(ツ)_/¯ platform not supported, expected

recent version `--platform=bazaar`
error:¯\_(ツ)_/¯ platform not supported, not expected

**Comment by benoitf** [comment]
Hello @mosn 

Issues have to be opened on the main Eclipse Che tracker as reported by Issues Templates else they're not triaged.

Here is the link to the tracker: https://github.com/eclipse/che

Please open it there, thx
