### ISSUE TITLE
customCheProperties in 7.41.2

### ISSUE THREAD

**Issue by gidduhome** [che-incubator/chectl#2433]
Hi,
Can someone from che team help me to find out list of all **customCheProperties** available in **eclipse-che** **7.41.2?**?

I looked at the documentation, but they are not available now. Is it possible to get them from any repo or older versions?
[This is the link I see](https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-components-properties-dashboard-settings).

What am I looking for is fields like below (but for version 7.41.2):

> CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "1800000"
>  CHE_LOGGER_CONFIG: org.eclipse.che.api.workspace.server.hc.HttpConnectionServerChecker=DEBUG

**Comment by nickboldt** [comment]
This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at https://github.com/eclipse/che/issues.
