### ISSUE TITLE
Che Mac Docker Desktop Nothing happen

### ISSUE THREAD

**Issue by emircanerkul** [che-incubator/chectl#2546]
After I type server:start

➜  ~ chectl server:start                                            
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...[1.25]
  ✔ Start following Eclipse Che installation logs...[OK]
  ✔ Scale Eclipse Che up
Command server:start has completed successfully in 00:00.

Says everything good but nothing happen

**Comment by nickboldt** [comment]
Did you deploy first? What OS/platform/arch? what version of docker desktop? 

More details needed. 

This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at https://github.com/eclipse/che/issues.
