### ISSUE TITLE
Telemetry should never send country as an array

### ISSUE THREAD

**Issue by fbricon** [che-incubator/chectl#2720]
https://github.com/che-incubator/chectl/blob/ee728618fabf8e2ad3cfbcaf47410c002b05d6a3/src/hooks/analytics/segment-adapter.ts#L141

Segment fails to send some events to amplitude because `Country must be a string but it was an array.`. Here's an example of a problematic payload received:
```
{
  “_metadata”: {
    “nodeVersion”: “16.13.2”
  },
  “anonymousId”: “....”,
  “channel”: “server”,
  “context”: {
    “app”: {
      “name”: “chectl”
    },
    “ip”: “0.0.0.0”,
    “library”: {
      “name”: “analytics-node”,
      “version”: “6.2.0"
    },
    “locale”: “en-US”,
    “location”: {
      “country”: []
    },
    “os”: {
      “name”: “linux”,
      “version”: “5.15.0-75-generic”
    },
    “timezone”: “UTC”
  },
  “event”: “server deploy”,
  “integrations”: {
    “All”: true
  },
 ...
  “properties”: {
    “command”: “server:deploy”,
    “platform”: “minikube”,
    “version”: “7.69.0"
  },
...
}
``` 

Those events were received in Woopra, but Amplitude is missing about 22% of those due to that error. Can you please fix it ASAP?
Thanks.

**Comment by ibuziuk** [comment]
fixed by https://github.com/che-incubator/chectl/pull/2721
