### ISSUE TITLE
Rename release assets for enabling to install them easily by script

### ISSUE THREAD

**Issue by suzuki-shunsuke** [che-incubator/chectl#2745]
I have a suggestion about GitHub Releases' asset names.

The latest release https://github.com/che-incubator/chectl/releases/tag/20230922071843 changed asset names.

chectl-v0.0.20230922-next-20ff59c-darwin-arm64.tar.gz
chectl-v0.0.20230922-next-20ff59c-darwin-x64.tar.gz
chectl-v0.0.20230922-next-20ff59c-linux-arm.tar.gz
chectl-v0.0.20230922-next-20ff59c-linux-ppc64le.tar.gz
chectl-v0.0.20230922-next-20ff59c-linux-s390x.tar.gz
chectl-v0.0.20230922-next-20ff59c-linux-x64.tar.gz
chectl-v0.0.20230922-next-20ff59c-win32-x64.tar.gz
chectl-v0.0.20230922-next-20ff59c-win32-x86.tar.gz

Previous version https://github.com/che-incubator/chectl/tree/20230919080737

chectl-darwin-arm64.tar.gz
chectl-darwin-x64.tar.gz
chectl-linux-arm.tar.gz
chectl-linux-ppc64le.tar.gz
chectl-linux-s390x.tar.gz
chectl-linux-x64.tar.gz
chectl-win32-x64.tar.gz
chectl-win32-x86.tar.gz

If you install this tool by script and will update the tool, you need to update not only the version but also the asset name.
And probably the part `20ff59c` will be changed so it is difficult to update the version automatically by Renovate or something.

So could you simplify asset names?

Thank you.

**Comment by suzuki-shunsuke** [comment]
Let me complement the background.
I'm a maintainer of [aqua](https://aquaproj.github.io/), which is a declarative CLI version manager.
aqua supports this tool, but the support was broken by the latest release of chectl.

- https://github.com/aquaproj/aqua-registry/pull/15647

https://github.com/aquaproj/aqua-registry/blob/02ae2e8c10a99961b44e4d2a78af22a3cb3228b8/pkgs/che-incubator/chectl/registry.yaml#L7

```yaml
asset: chectl-{{.OS}}-{{.Arch}}.tar.gz
```

aqua has no way to know the part `20ff59c`, so aqua can't support this tool.
So I really appreciate it if you consider simplifying asset names.

**Comment by tolusha** [comment]
Hello, @suzuki-shunsuke 
https://github.com/che-incubator/chectl/pull/2769 should we the problem

**Comment by suzuki-shunsuke** [comment]
Oh, thank you.

**Comment by suzuki-shunsuke** [comment]
Confirmed the issue has been solved at the latest release.
https://github.com/che-incubator/chectl/releases/tag/20230927123504
