### ISSUE TITLE
Text color not reset properly on ConEmu Windows

### ISSUE THREAD

**Issue by qurben** [che-incubator/chectl#42]
When running chectl on powershell in [ConEmu](https://conemu.github.io/) the text in te console is changed to black and not reset afterwards. On cmd in ConEmu the text is black but the color of the prompt is not changed. This issue is not present in (vanilla) powershell or cmd.

![](https://i.imgur.com/ssxFLE7.png)

**Comment by l0rd** [comment]
@qurben Thanks for tracking this. I need to check what's causing this problem. We are using [the Heroku oclif framework](https://oclif.io/) for the CLI commands and the JavaScript library Listr to display the fancy task list when you run `chectl server:start`

**Comment by l0rd** [comment]
@qurben can you reproduce the problem even when you try `chectl --help`?

**Comment by qurben** [comment]
Yes, this also happens with `chectl --help`
![image](https://user-images.githubusercontent.com/589651/53008972-c5099d80-343a-11e9-9bbc-1141f520ed88.png)

I'll try the oclif example app to see if that causes problems.

**Comment by qurben** [comment]
This is an issue with oclif, I filed an issue at their repo https://github.com/oclif/oclif/issues/208.
