### ISSUE TITLE
Add more inject options: git, bash and ssh configs

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#44]
We currently support the [injection of local Kube configiburation](https://github.com/che-incubator/chectl#chectl-workspaceinject) inside workspace containers. It may be intersting to inject other configs as well.

```
chectl workspace:inject --gitconfig           Inject local git configuration
chectl workspace:inject --sshconfig           Inject local ssh configuration
chectl workspace:inject --bashconfig          Inject local bash configuration
```

**Comment by sunix** [comment]
Not sure it is a good idea to get the .gitconfig .bashrc or .ssh folder from your local home folder.
My .gitconfig contains some references to tools that may not be present in the workspace containers (for instance I use meld as a difftool which is a desktop app, meld wouldn't be used in Che)
My bashrc contains more than just PS1 but also PATH configuration, JAVA_HOME env variables etc .. that would not work on the containers in Che.
Last but not least, for security reason, i don't want my ssh private key to be available in a file system somewhere in the Cloud.

**Comment by l0rd** [comment]
@sunix note that injection won't happen without an explicit user command. 

What I mean is that users will start their workspace (`chectl workspace:start --devfile=${DEVFILE_PATH}`) and then, if they want to, inject some local configuration (`chectl workspace:inject --bashconfig`).

That said we could think about a way to sanitize `.bashrc` or `.gitconfig` (i.e. comment out lines where there is a local path) and provide a warning when the user ask to import its `.ssh` configuration.

**Comment by l0rd** [comment]
@sunix anyway you points are good ones

**Comment by sunix** [comment]
ok to me these are user settings, files that would go the the home folder of a container.
What about a command like
```
chectl workspace:inject --userconfig /home/user/github/myCheUserConfigFiles/
```
where ` /home/user/github/myCheUserConfigFiles/` could contain a .bashrc, .gitconfig, .ssh folder and maybe more ?

My overthinking: could we have a Github project in our user space named `che-personal-settings` (for instance http://github.com/sunix/che-user-settings for me) where we could store all these stuff ? The only thing the user would have to do is link his Github account to his Che account. This repo could also store factories/devfiles that would be magically available in the dashboard, Che commands that would be available in any workspace, etc ....
