### ISSUE TITLE
MicroK8s support

### ISSUE THREAD

**Issue by bohushvitali** [che-incubator/chectl#49]
References:

- https://github.com/ubuntu/microk8s
- https://codefresh.io/kubernetes-tutorial/local-kubernetes-linux-minikube-vs-microk8s/

**Comment by l0rd** [comment]
@bohushvitali that's currently not in our roadmap but I am +1 if you want to provide a PR

**Comment by sleshchenko** [comment]
@l0rd @benoitf Isn't it implemented in https://github.com/che-incubator/chectl/pull/146
