### ISSUE TITLE
Che server startup fails as keycloak is not accessible

### ISSUE THREAD

**Issue by rahulkiit** [che-incubator/chectl#526]
When i am trying to deploy the che server on DO cluster somehow keycloak url is not accessible from che server pod and so che server start is failing. I can access the keycloak url from my machine but che host pod is not able to access it.

I tried curl command from the che pod but keycloak url is not accessible. 

Install command :  chectl server:start --installer=helm --platform=k8s --tls  --domain=<domain name>

Retrieving OpenId configuration from endpoint: https://keycloak domain/auth/realms/che/.well-known/openid-configuration

**Comment by sleshchenko** [comment]
I guess you use self-signed cert.
If yes - you should  create secret `self-signed-cert` with CA cert inside and then redeploy che with `add --self-signed-cert` flag, like `chectl server:start --installer=helm --platform=k8s --tls --self-signed-cert --domain=`

**Comment by rahulkiit** [comment]
No. I am not using self-signed cert.

Keycloak url is accessible from my machine but it is not accessible from che pod. If i use curl statement with pod ip then it work but when i use the dns url then it don't work.

**Comment by sparkoo** [comment]
@rahulkiit please report the issue to the main Che repo https://github.com/eclipse/che/issues

**Comment by sleshchenko** [comment]
@rahulkiit and please provide more info about your cluster installations. Seems it's not Che issue and cluster configuration, but hopefully we'll be able to help you solve it.

**Comment by nickboldt** [comment]
This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at https://github.com/eclipse/che/issues.
