### ISSUE TITLE
Che installation fails during execution of CI job 

### ISSUE THREAD

**Issue by musienko-maxim** [che-incubator/chectl#53]
**Environment:** VM on OpenStack  RHEL7 with 16GB memory, minikube based on KVM, chectl v. 0.0.2 linux-x64 node-v10.4.1 
 [CI job:](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-happy-path/)
**Info about reproducing:** This usually happens on CI job after successful launching of minikube with 10GD RAM.
**Expected result:**  The CHE should be deployed on minikube and available
**Actual result:** We have error like: `Command failed: helm init --service-account tiller --wait`

<details>
 <summary>Log  from CI</summary>
 <pre>
/chectl server:start
17:51:35 [11:51:35] Platform preflight checklist (minikube) ✈️ [started]
17:51:35 [11:51:35] Verify if kubectl is installed [started]
17:51:35 [11:51:35] Verify if kubectl is installed [completed]
17:51:35 [11:51:35] Verify if minikube is installed [started]
17:51:35 [11:51:35] Verify if minikube is installed [completed]
17:51:35 [11:51:35] Verify if minikube is running [started]
17:51:35 [11:51:35] Verify if minikube is running [completed]
17:51:35 [11:51:35] Start minikube [started]
17:51:35 [11:51:35] Start minikube [skipped]
17:51:35 [11:51:35] → Minikube is already running.
17:51:35 [11:51:35] Verify if minikube ingress addon is enabled [started]
17:51:35 [11:51:35] Verify if minikube ingress addon is enabled [completed]
17:51:35 [11:51:35] Enable minikube ingress addon [started]
17:51:36 [11:51:36] Enable minikube ingress addon [completed]
17:51:36 [11:51:36] Retrieving minikube IP and domain for ingress URLs [started]
17:51:41 [11:51:41] Retrieving minikube IP and domain for ingress URLs...192.168.39.203.nip.io. [title changed]
17:51:41 [11:51:41] Retrieving minikube IP and domain for ingress URLs...192.168.39.203.nip.io. [completed]
17:51:41 [11:51:41] Platform preflight checklist (minikube) ✈️ [completed]
17:51:41 [11:51:41] Running the installer (Helm) 🏎️ [started]
17:51:41 [11:51:41] Verify if helm is installed [started]
17:51:41 [11:51:41] Verify if helm is installed [completed]
17:51:41 [11:51:41] Create Tiller Role Binding [started]
17:51:41 [11:51:41] Create Tiller Role Binding...done. [title changed]
17:51:41 [11:51:41] Create Tiller Role Binding...done. [completed]
17:51:41 [11:51:41] Create Tiller Service Account [started]
17:51:41 [11:51:41] Create Tiller Service Account...done. [title changed]
17:51:41 [11:51:41] Create Tiller Service Account...done. [completed]
17:51:41 [11:51:41] Create Tiller RBAC [started]
17:51:42 [11:51:41] Create Tiller RBAC [completed]
17:51:42 [11:51:41] Create Tiller Service [started]
17:52:02 [11:52:01] Create Tiller Service [failed]
17:52:02 [11:52:01] → Command failed: helm init --service-account tiller --wait
17:52:02 
17:52:02 Creating /home/hudson/.helm 
17:52:02 Creating /home/hudson/.helm/repository 
17:52:02 Creating /home/hudson/.helm/repository/cache 
17:52:02 Creating /home/hudson/.helm/repository/local 
17:52:02 Creating /home/hudson/.helm/plugins 
17:52:02 Creating /home/hudson/.helm/starters 
17:52:02 Creating /home/hudson/.helm/cache/archive 
17:52:02 Creating /home/hudson/.helm/repository/repositories.yaml 
17:52:02 Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
17:52:02 Adding local repo with URL: http://127.0.0.1:8879/charts 
17:52:02 $HELM_HOME has been configured at /home/hudson/.helm.
17:52:02 
17:52:02 Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
17:52:02 
17:52:02 Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
17:52:02 To prevent this, run `helm init` with the --tiller-tls-verify flag.
17:52:02 For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
17:52:02 
17:52:02 [11:52:01] Running the installer (Helm) 🏎️ [failed]
17:52:02 [11:52:01] → Command failed: helm init --service-account tiller --wait
17:52:02 
17:52:02 Creating /home/hudson/.helm 
17:52:02 Creating /home/hudson/.helm/repository 
17:52:02 Creating /home/hudson/.helm/repository/cache 
17:52:02 Creating /home/hudson/.helm/repository/local 
17:52:02 Creating /home/hudson/.helm/plugins 
17:52:02 Creating /home/hudson/.helm/starters 
17:52:02 Creating /home/hudson/.helm/cache/archive 
17:52:02 Creating /home/hudson/.helm/repository/repositories.yaml 
17:52:02 Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
17:52:02 Adding local repo with URL: http://127.0.0.1:8879/charts 
17:52:02 $HELM_HOME has been configured at /home/hudson/.helm.
17:52:02 
17:52:02 Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
17:52:02 
17:52:02 Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
17:52:02 To prevent this, run `helm init` with the --tiller-tls-verify flag.
17:52:02 For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
17:52:02 
17:52:02 Error: Command failed: helm init --service-account tiller --wait
17:52:02 Creating /home/hudson/.helm 
17:52:02 Creating /home/hudson/.helm/repository 
17:52:02 Creating /home/hudson/.helm/repository/cache 
17:52:02 Creating /home/hudson/.helm/repository/local 
17:52:02 Creating /home/hudson/.helm/plugins 
17:52:02 Creating /home/hudson/.helm/starters 
17:52:02 Creating /home/hudson/.helm/cache/archive 
17:52:02 Creating /home/hudson/.helm/repository/repositories.yaml 
17:52:02 Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
17:52:02 Adding local repo with URL: http://127.0.0.1:8879/charts 
</pre>
</details>

**Comment by l0rd** [comment]
It's the same error as reported https://github.com/che-incubator/chectl/issues/27

It's a timeout error (if the command hasn't terminated after 10s it fails)

I will provide a fix today for this one

**Comment by musienko-maxim** [comment]
Ok thanks,  I am looking forward to...

**Comment by l0rd** [comment]
@musienko-maxim for your information PR #45 with the fix for this issue has been merged
