### ISSUE TITLE
Remove option for different install types on minishift

### ISSUE THREAD

**Issue by tsmaeder** [che-incubator/chectl#60]
There is a parameter to use different ways to install che when using "chectl server:start" (operator, helm and something more I forget).

I don't see a reason to have more than one option there. My proposal is to always use the same method to install che.

**Comment by l0rd** [comment]
A user can already avoid to specify the installer (you can `chectl server:start --platform minishift` for instance) so I am not sure I understand your request. I am assuming that you are suggesting to always use the same installer for an easier maintenance but that's not possible yet. Let me try to explain why I think so.

Currently the installer option accepts the values `helm`, `operator` and `minishift-addon`. If I understand correctly you are suggesting to remove option `--installer` and always use the same installer. 

We could for instance always use the `operator` installer. But it doesn't support single user Che and it's the best option for local development.

We could use always use `helm`. But it doesn't support OpenShift.

As a consequence if we want to support both OpenShift and single user Che we can't always use the same installer (yet). That may change when the operator will support single user Che.

**Comment by tsmaeder** [comment]
Yes, but none of these things are anything the user wants to decide. If the best installer to use is determined by other factors (OpenShift or Kubernetes, single- or multi-user), it should be inferred from those other parameters. We're just giving the user an opportunity to screw up (by operator with single user, for example)

**Comment by benoitf** [comment]
Kamino closed and cloned this issue to [eclipse/che](https://github.com/eclipse/che/issues/14467)
