### ISSUE TITLE
Error: Error: Platform is required ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by NGC-6121** [che-incubator/chectl#645]
![image](https://user-images.githubusercontent.com/55633909/79399211-55972b80-7fb5-11ea-8b66-4470996737c2.png)

P.S. 
![image](https://user-images.githubusercontent.com/55633909/79399270-7c556200-7fb5-11ea-81e3-45d274e0d3fa.png)

**Comment by ntziolis** [comment]
I have the same issue. Trying to run the `server:deploy` command on Windows 10 with WSL 2.

**Comment by dheerajbhaskar** [comment]
I also encountered this. Here is the solution.

This is crazy that this is undocumented. I had to go through the source code

```
char: 'p',
description: 'Type of Kubernetes platform. Valid values are \"minikube\", \"minishift\", \"k8s (for kubernetes)\", \"openshift\", \"crc (for CodeReady Containers)\", \"microk8s\".',
        options: ['minikube', 'minishift', 'k8s', 'openshift', 'microk8s', 'docker-desktop', 'crc'],
```

So you need to pass in the platform like so
```
chectl server:deploy -p "minikube"
```

**Comment by tuyennv6** [comment]
> I also encountered this. Here is the solution.
> 
> This is crazy that this is undocumented. I had to go through the source code
> 
> ```
> char: 'p',
> description: 'Type of Kubernetes platform. Valid values are \"minikube\", \"minishift\", \"k8s (for kubernetes)\", \"openshift\", \"crc (for CodeReady Containers)\", \"microk8s\".',
>         options: ['minikube', 'minishift', 'k8s', 'openshift', 'microk8s', 'docker-desktop', 'crc'],
> ```
> 
> So you need to pass in the platform like so
> 
> ```
> chectl server:deploy -p "minikube"
> ```
Your solution is great.

**Comment by nickboldt** [comment]
It's documented if you use the --help flag: 

```
bash-5.1# ./bin/run server:deploy --help
Deploy Eclipse Che server

USAGE
  $ chectl server:deploy

OPTIONS
  -b, --domain=domain
      Domain of the Kubernetes cluster (e.g. example.k8s-cluster.com or <local-ip>.nip.io)
      This flag makes sense only for Kubernetes family infrastructures and will be autodetected for Minikube and MicroK8s in most cases.
      However, for Kubernetes cluster it is required to specify.
      Please note, that just setting this flag will not likely work out of the box.
      According changes should be done in Kubernetes cluster configuration as well.
      In case of Openshift, domain adjustment should be done on the cluster configuration level.

  -d, --directory=directory
      Directory to store logs into

  -h, --help
      show CLI help

  -i, --cheimage=cheimage
      Eclipse Che server container image

  -n, --chenamespace=chenamespace
      Eclipse Che Kubernetes namespace.

  -p, --platform=minikube|k8s|openshift|microk8s|docker-desktop|crc
      (required) Type of Kubernetes platform.
```

So... I'm going to close this as "working & documented in the app itself".
