### ISSUE TITLE
Issues need to be filed in the main Eclipse Che repository

### ISSUE THREAD

**Issue by hari1992-web** [che-incubator/chectl#652]
## Where to report issues?

This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at [https://github.com/eclipse/che/issues](https://github.com/eclipse/che/issues).

**Comment by hari1992-web** [comment]
Readiness probe failed: HTTP probe failed with statuscode: 500
Back-off restarting failed container 
![Screenshot from 2020-04-17 18-24-36](https://user-images.githubusercontent.com/62592574/79571398-c125e980-80d8-11ea-9342-62417d1fb010.png)

**Comment by hari1992-web** [comment]
Does any way fix it ?? Thanks in advance

**Comment by sleshchenko** [comment]
@hari1992-web Please take a look an issue description ;)

![Screenshot_20200421_134359](https://user-images.githubusercontent.com/5887312/79857250-2b3ed700-83d6-11ea-8f10-90a5d5bc447e.png)

Please create the issue in the Che repo and don't forget to attach Che Server logs there.

**Comment by nickboldt** [comment]
Closing.

This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at https://github.com/eclipse/che/issues.
