### ISSUE TITLE
./install.sh: line 224: RED: unbound variable

### ISSUE THREAD

**Issue by olberger** [che-incubator/chectl#653]
Trying this yields an error:
```
$ ./install.sh --help
./install.sh: line 224: RED: unbound variable
```

Hth

**Comment by nickboldt** [comment]
More context would be useful to know what you're doing, why, and on what OS, etc.

This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at https://github.com/eclipse/che/issues.
