### ISSUE TITLE
setup-che-in-tls-mode-with-self-signed-certificate doc page 404

### ISSUE THREAD

**Issue by olberger** [che-incubator/chectl#654]
The instrutions provided by chectl point to  https://www.eclipse.org/che/docs/che-7/setup-che-in-tls-mode-with-self-signed-certificate/ which is now 404.

I believed this could be changed to https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/
Hth

**Comment by mmorhun** [comment]
@olberger I've moved this issue into Che repository as we track all Eclipse Che related issue there.

**Comment by olberger** [comment]
I'm afraid this makes poor sense, as the involved code lives here AFAIU... but you're of course free to manage issues whichever way you prefer ;-)

**Comment by mmorhun** [comment]
@olberger there was a discussion about where we should keep Eclipse Che related issues: in components repositories or in main Che repo. But in the end we decided to keep everything in one place as it is much easier to track. it is not my own decision...
Anyway, thanks for letting us know. We'll fix this one soon.
