### ISSUE TITLE
chectl server:start fails even if minishift is started

### ISSUE THREAD

**Issue by jeffmaury** [che-incubator/chectl#66]
My minishift is started but seems the minishift status command is using more than 10s to complete.

**Comment by benoitf** [comment]
hello, 

it's working after 10s or there is a timeout error after these 10s ?

**Comment by jeffmaury** [comment]
No this causes the server:start command to fail

**Comment by jeffmaury** [comment]
Now working with my PR

**Comment by benoitf** [comment]
If minishift is not running, then it will take 60s to see that it's not started ?

**Comment by jeffmaury** [comment]
No minishift was runnnig but command minishift status to 14 to 15s
