### ISSUE TITLE
Pkg: FLAGS_MISMATCH

### ISSUE THREAD

**Issue by opiation** [che-incubator/chectl#74]
A fresh install of `chectl` with `minikube`, `kubectl` and `minikube` running on virtualbox gives:

```shell
Pkg: FLAGS_MISMATCH
```
Any invocation of `chectl` in the command line responds as such.

This is happening because this machine has the `NODE_OPTIONS` environment variable set to `--max-old-space-size=2048`.  Removing the env var with `unset NODE_OPTIONS` addresses the issue.

It is nonetheless common for JS developers using webpack to have this env var set as such.  There may be room for config improvement here for `chectl` like gracefully handling an existing `NODE_OPTIONS` environment variable or at least warning the user of this limitation.

**Comment by benoitf** [comment]
thk @opiation for the report. It's now fixed in new releases of the CLI

**Comment by opiation** [comment]
Wonderful!  Thanks for such a responsive and quick turnaround, @benoitf.
