### ISSUE TITLE
Wrong default image tag is wrong when starting Che Server on minishift platform

### ISSUE THREAD

**Issue by sleshchenko** [che-incubator/chectl#87]
Wrong default image tag is wrong when starting Che Server on minishift platform.

### How to reproduce
1. Start minishift.
2. Deploy Che to minishift with the following parameters:
```
./bin/run server:start --platform=minishift
```
![Screenshot_20190424_151024](https://user-images.githubusercontent.com/5887312/56658359-1e908180-66a3-11e9-8a6c-547408b59d9f.png)
3. Check is Che Server is started from correct default image which is `nightly`.
**Expected**: Che Server is deployed with `eclipse/che-server:nightly`
**Actual**: Che Server is deployed with `eclipse/che-server:latest`
![Screenshot_20190424_151125](https://user-images.githubusercontent.com/5887312/56658416-42ec5e00-66a3-11e9-8f76-a77356446670.png)

## Diagnostics
```bash
serg@sergpad:~/projects/chectl$ minishift version
minishift v1.33.0+ba29431
```

**Comment by benoitf** [comment]
hello, why is it wrong ?

**Comment by sleshchenko** [comment]
Because nightly should be default one, as help says
![Screenshot_20190424_151430](https://user-images.githubusercontent.com/5887312/56658592-b1312080-66a3-11e9-8205-2ca0b8899a7a.png)
And code contains `nightly` as well
https://github.com/che-incubator/chectl/blob/66ce104c6b65c9eb39cde1af70ede08e84516c1f/src/commands/server/start.ts#L40

**Comment by benoitf** [comment]
ok understood now 👍

**Comment by benoitf** [comment]
it provides the command
```
minishift addon apply --addon-env NAMESPACE=che --addon-env CHE_IMAGE_REPO=eclipse/che-server --addon-env CHE_IMAGE_TAG=nightly che
```

is https://github.com/minishift/minishift/tree/master/addons/che#deploy-a-custom-che-server-image not acurate ?

**Comment by sleshchenko** [comment]
> is https://github.com/minishift/minishift/tree/master/addons/che#deploy-a-custom-che-server-image not acurate ?

I think the cause may be in minishift addon but not chectl. Needs to be investigated.

**Comment by benoitf** [comment]
![image](https://user-images.githubusercontent.com/436777/56662429-374d6700-66a4-11e9-89f6-c44e24743ca2.png)


on my side I've che-server:nightly

**Comment by benoitf** [comment]
@sleshchenko do you have some environment variables defined ?

**Comment by sleshchenko** [comment]
Some but not `CHE_IMAGE_TAG` 
![Screenshot_20190424_162129](https://user-images.githubusercontent.com/5887312/56662666-3240e580-66ad-11e9-9cd2-cd4f17164b91.png)

**Comment by benoitf** [comment]
do you have the same error when doing 
```shell
$ minishift addon apply --addon-env NAMESPACE=che --addon-env CHE_IMAGE_REPO=eclipse/che-server --addon-env CHE_IMAGE_TAG=nightly che
```
?

**Comment by sleshchenko** [comment]
Thank @l0rd! We found an issue. It's `~/.minishift/addons/che`. Looks like it is not removed even after `minishift delete`.
We decided that cached minishift addon is a little issue that we won't handle since we're planning to use the only operator for installation on minishift.
