### ISSUE TITLE
chectl fails to deploy Che on minishift

### ISSUE THREAD

**Issue by mmorhun** [che-incubator/chectl#91]
#### Steps to reproduce
1. Create minishift VM with command:
```
minishift start --vm-driver=virtualbox --cpus=4 --memory=16192 --disk-size=50GB --docker-opt userland-proxy=false
```
2. Run `chectl`:
```
chectl server:start --platform=minishift
```

**Expected:** Che is deplayed on minishift
**Actual:** `chectl` fails with error:
```
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Verify userland-proxy is disabled...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.104.nip.io.
  ✔ 🏃‍  Running the Che minishift-addon
    ✔ Apply Che addon...done.
  ❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✖ scheduling
        → pods is forbidden: User "developer" cannot list pods in the namespace "che": no RBAC policy matched
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: pods is forbidden: User "developer" cannot list pods in the namespace "che": no RBAC policy matched
    at KubeHelper.<anonymous> (~/projects/chectl/src/api/kube.ts:183:43)
    at Generator.throw (<anonymous>)
    at rejected (~/projects/chectl/src/api/kube.ts:15:65)
    at <anonymous>
```

_Minishift version:_ minishift v1.33.0+ba29431

**Comment by amisevsk** [comment]
Sometimes the error message when you're technically not logged in is obtuse; could you try running `oc login -u developer` before the chectl command?

**Comment by mmorhun** [comment]
Thank you for response. Unfortunately that didn't help. I've seen message that I am logged in, but the error is still remain.

**Comment by mmorhun** [comment]
With @sleshchenko figured out that despite chectl reports `✔ Apply Che addon...done.` the addon is not applied:
```
[mmorhun@host chectl]$ minishift addon apply --addon-env NAMESPACE=che che
No add-on with the name 'che' is installed.
[mmorhun@host chectl]$ echo $?
0
```

**Comment by amisevsk** [comment]
@mmorhun Ah that's a funny way to get an error. Which version of minishift are you using? AFAIK `che` has been a default addon for a while.

Try `minishift addon install che` and then executing the script.

**Comment by mmorhun** [comment]
Yes, after installing che addon it works

**Comment by mmorhun** [comment]
Well, we need to add check for it :)

**Comment by benoitf** [comment]
@mmorhun @amisevsk che addon is not already a minishift-addon (no need to install it separately ?)

You don't have the addon in your `$HOME/.minishift/addons` folder ?

**Comment by mmorhun** [comment]
AFAIK it is, but I didn't have it installed (I deleted it while was performing some experiments).

**Comment by benoitf** [comment]
@mmorhun ok thx, so you were both logged out and you deleted `che` minishift addon
